### ISSUE TITLE
Fail to make project because of mLib.

### ISSUE THREAD

**Issue by Jie2World** [nonlinear1/BundleFusion_Ubuntu_V0#1]
I try to build the project and cmake it successfully, but the errors occured because of mLib when i make it. I replaced the empty document with the one from https://github.com/niessner/mLib.
All errors are 'xxx was not declared in the scope'. Can you update your mLib?  Or tell us how to fix it?

**Comment by nonlinear1** [comment]
I will fix it.

**Comment by nonlinear1** [comment]
I cann't push the file to BundleFusion_Ubuntu_V0 project, for some unknow reasons. So you can send me a email! deansaint@126.com then I will give you my changed version mLib!

**Comment by nonlinear1** [comment]
"external" in this folder there is a mLib library, which is changed by me,and this folder is necessary. I don't know why I can't push the folder to my project. For now, someone who want run this project can send me a email, I will give you my changed version mLib library! my email: deansaint@126.com
