### ISSUE TITLE
 Errors at FreeImage.h.

### ISSUE THREAD

**Issue by Jie2World** [nonlinear1/BundleFusion_Ubuntu_V0#3]
![Screenshot from 2019-11-28 10-31-55](https://user-images.githubusercontent.com/20303947/69776741-5b43ce80-11d8-11ea-9733-fea4126a0118.png)
I met some errors at FreeImage.h. For example, 'WORD' does not name a type.

**Comment by Jie2World** [comment]
I fixed it by making some commented-out code at FreeImage.h work again. 
`#ifndef _MSC_VER
// define portable types for 32-bit / 64-bit OS
#include <inttypes.h>
typedef int32_t BOOL;
typedef uint8_t BYTE;
typedef uint16_t WORD;
typedef uint32_t DWORD;
typedef int32_t LONG;
typedef int64_t INT64;
typedef uint64_t UINT64;
#else
// MS is not C99 ISO compliant
typedef long BOOL;
typedef unsigned char BYTE;
typedef unsigned short WORD;
typedef unsigned long DWORD;
typedef long LONG;
typedef signed __int64 INT64;
typedef unsigned __int64 UINT64;
#endif // _MSC_VER`

And move some codes out of #ifdef FREEIMAGE_STRUCTS_DEFINED_ 
`typedef struct tagRGBQUAD {
#if FREEIMAGE_COLORORDER == FREEIMAGE_COLORORDER_BGR
  BYTE rgbBlue;
  BYTE rgbGreen;
  BYTE rgbRed;
#else
  BYTE rgbRed;
  BYTE rgbGreen;
  BYTE rgbBlue;
#endif // FREEIMAGE_COLORORDER
  BYTE rgbReserved;
} RGBQUAD;`

`typedef struct tagBITMAPINFOHEADER{
  DWORD biSize;
  LONG  biWidth; 
  LONG  biHeight; 
  WORD  biPlanes; 
  WORD  biBitCount;
  DWORD biCompression; 
  DWORD biSizeImage; 
  LONG  biXPelsPerMeter; 
  LONG  biYPelsPerMeter; 
  DWORD biClrUsed; 
  DWORD biClrImportant;
} BITMAPINFOHEADER, *PBITMAPINFOHEADER; 

typedef struct tagBITMAPINFO { 
  BITMAPINFOHEADER bmiHeader; 
  RGBQUAD          bmiColors[1];
} BITMAPINFO, *PBITMAPINFO;`

It work, but it isn't a graceful way,
Hope it will help.

**Comment by Quitino** [comment]
I encountered the same problem, thank you very much.
